[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://ttsai-backend-321805997355.us-central1.run.app/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 