steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ttsai-461209/ttsai-backend', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ttsai-461209/ttsai-backend']

images:
  - 'gcr.io/ttsai-461209/ttsai-backend' 